title = 'Storehouse Management 用户手册'
evergreen = true
base = '/'

[locales]
'/' = { lang = 'default', title = 'Storehouse Management Manual' }
'/zh-cn/' = { lang = 'zh-CN', title = 'Storehouse Management 用户手册' }
'/en-us/' = { lang = 'en-US', title = 'Storehouse Management Manual' }

[themeConfig]
repo = 'wms-community/storehouse-management-manual'
docsBranch = 'master'
docsDir = 'post'
editLinks = true

[themeConfig.locales.'/']
selectText = 'Languages'
label = 'Home'
docsDir = 'post'

[themeConfig.locales.'/zh-cn/']
selectText = '选择语言'
label = '简体中文'
docsDir = 'post'
editLinkText = '帮助我们完善这个页面'
lastUpdated = '最后更新'
sidebar = [
  '/zh-cn/install',
  '/zh-cn/faq',
  '/zh-cn/report',
  '/zh-cn/dir',
  '/zh-cn/env',
  '/zh-cn/build',
  '/zh-cn/versions',
  '/zh-cn/upgrade-guide',
  '/zh-cn/change-log',
  '/zh-cn/update-sources',
  '/zh-cn/cdn',
]
[[themeConfig.locales.'/zh-cn/'.nav]]
text = 'Storehouse Management'
link = '/zh-cn/'
[[themeConfig.locales.'/zh-cn/'.nav]]
text = 'API'
link = '/zh-cn/api/'

[themeConfig.locales.'/en-us/']
selectText = 'Languages'
label = 'English'
docsDir = 'post/en'
editLinkText = 'Edit this page on GitHub'
lastUpdated = 'Last Updated'
sidebar = [
  
]
