title = 'Storehouse Management 用户手册'
evergreen = true

[locales]
'/' = { lang = 'default', title = 'Storehouse Management Manual' }
'/zh-cn/' = { lang = 'zh-CN', title = 'Storehouse Management 用户手册' }
'/en-us/' = { lang = 'en-US', title = 'Storehouse Management Manual' }

[themeConfig]
repo = 'wms-community/storehouse-management-manual'
docsBranch = 'master'
docsDir = 'post'
editLinks = true

[themeConfig.locales.'/']
selectText = '选择语言'
label = '简体中文'
docsDir = 'post'
editLinkText = '帮助我们完善这个页面'
lastUpdated = '最后更新'

[[themeConfig.locales.'/'.nav]]
text = 'Storehouse Management'
link = '/'

[themeConfig.locales.'/'.sidebar]
'/' = [
  '/zh/install',
  '/zh/faq',
  '/zh/report',
  '/zh/env',
]

[themeConfig.locales.'/en/']
selectText = 'Languages'
label = 'English'
docsDir = 'post/en'
editLinkText = 'Edit this page on GitHub'
lastUpdated = 'Last Updated'
sidebar = [
  
]
