title = 'Storehouse Management 用户手册'
evergreen = true

[locales]
'/' = { lang = 'zh-CN', title = 'Storehouse Management 用户手册' }
'/en-us/' = { lang = 'en-US', title = 'Storehouse Management Manual' }

[themeConfig]
repo = 'wms-community/storehouse-management-manual'
docsBranch = 'master'
docsDir = 'man'
editLinks = true

[themeConfig.locales.'/']
selectText = '选择语言'
label = '简体中文'
docsDir = 'man'
editLinkText = '帮助我们完善这个页面'
lastUpdated = '最后更新'

[[themeConfig.locales.'/'.nav]]
text = 'Storehouse Management'
link = '/'
[[themeConfig.locales.'/'.nav]]
text = 'API'
link = '/api/'

[themeConfig.locales.'/'.sidebar]
'/api/' = [
  '/api/basis',
  '/api/oauth',
  '/api/auth',
  '/api/user',
  '/api/players',
  '/api/closet',
  '/api/avatars-and-previews',
]
'/' = [
  '/setup',
  '/faq',
  '/report',
  '/env',
  '/build',
  '/versions',
  '/upgrade-guide',
  '/change-log',
  '/update-sources',
  '/cdn',
  '/oauth',
  '/ucenter',
  '/flarum',
]

[themeConfig.locales.'/en-us/']
selectText = 'Languages'
label = 'English'
docsDir = 'man/en-us'
editLinkText = 'Edit this page on GitHub'
lastUpdated = 'Last Updated'
sidebar = [
  '/en-us/setup',
]
