title = 'Storehouse Management 用户手册'
evergreen = true

[locales]
'/' = { lang = 'zh-CN', title = 'Storehouse Management 用户手册' }
'/en-us/' = { lang = 'en-US', title = 'Storehouse Management Manual' }

[themeConfig]
repo = 'wms-community/storehouse-management-manual'
docsBranch = 'master'
docsDir = 'man'
editLinks = true

[themeConfig.locales.'/']
selectText = '选择语言'
label = '简体中文'
docsDir = 'man'
editLinkText = '帮助我们完善这个页面'
lastUpdated = '最后更新'

[[themeConfig.locales.'/'.nav]]
text = 'Storehouse Management'
link = '/'
[[themeConfig.locales.'/'.nav]]
text = 'Web API'
link = '/api/'

[themeConfig.locales.'/'.sidebar]
'/api/' = [
  '/api/bilding',
]
'/' = [
  '/setup',
  '/faq',
  '/report',
  '/dir',
  '/env',
  '/build',
  '/versions',
  '/upgrade-guide',
  '/change-log',
  '/update-sources',
  '/cdn',
  '/ucenter',
  '/oauth',
]

[themeConfig.locales.'/en/']
selectText = 'Languages'
label = 'English'
docsDir = 'man/en'
editLinkText = 'Edit this page on GitHub'
lastUpdated = 'Last Updated'
sidebar = [
  '/en/setup',
  '/en/faq',
  '/en/report',
  '/en/dir',
  '/en/build',
  '/en/upgrade-guide',
  '/en/change-log',
  '/en/versions',
  '/en/ucenter',
]
